from pptx import Presentation
from pptx.util import Inches
from pptx.util import Pt
from pptx.enum.text import PP_ALIGN
from pptx.enum.chart import XL_CHART_TYPE
import csv
import json
import argparse

pr1 = Presentation()

# Slide1
slide1_register = pr1.slide_layouts[0]
slide1 = pr1.slides.add_slide(slide1_register)

# Title1
title1 = slide1.shapes.title
title1.text = "The evolution of Ai"

title1_text_frame = title1.text_frame

# Font change
font = title1_text_frame.paragraphs[0].font
font.bold = True
font.italic = True
font.underline = False

# Subtitle1
subtitle1 = slide1.placeholders[1]
subtitle1.text = "And what may comes next"


subtitle1_text_frame = subtitle1.text_frame

# Font change
font = subtitle1_text_frame.paragraphs[0].font
font.name = "Arial"
font.size = Inches(0.3)
font.underline = True


# Img1
img1 = "title.jpg"
left = top = Inches(0)
pic1 = slide1.shapes.add_picture(img1, left, top, width = pr1.slide_width, height = pr1.slide_height)

# Img order
slide1.shapes._spTree.remove(slide1.shapes._spTree[-1])
slide1.shapes._spTree.insert(2, pic1._element)

# Slide2
slide2_register = pr1.slide_layouts[1]
slide2 = pr1.slides.add_slide(slide2_register)

# Title2
title2 = slide2.shapes.title
title2.text = "The beginning of AI"
title2.text_frame.paragraphs[0].font.size = Pt(30)
title2.text_frame.paragraphs[0].alignment = PP_ALIGN.LEFT

# Content - long text
content1_box = slide2.placeholders[1]
content1_box.text = "AI's captivating history traces back to ancient myths. Its formal pursuit started in 1956, leading to rule-based systems and the first 'AI winter.' In the 1980s, AI resurged with machine learning breakthroughs, like neural networks and deep learning. Today, AI drives innovations across industries, with a promising future ahead."
content1_box.text_frame.paragraphs[0].font.size = Inches(0.3)

# Background img
background_img = "wallpaper.png"
left = top = Inches(0)
pic2 = slide2.shapes.add_picture(background_img, left, top, width = pr1.slide_width, height = pr1.slide_height)

slide2.shapes._spTree.insert(2, pic2._element)

# Slide 3 - List
slide3_register = pr1.slide_layouts[1]
slide3 = pr1.slides.add_slide(slide3_register)

slide3.shapes.title.text = "Introduction to AI"
content_box = slide3.placeholders[1]
text_frame = content_box.text_frame

list_items = ["1. Definition of AI", "2. Types of AI", "3. Applications of AI", "4. Importance of AI"]
for item in list_items:
    p = text_frame.add_paragraph()
    p.text = item
    p.space_after = Pt(5)

# Background img

background_img = "wallpaper.png"
left = top = Inches(0)
pic3 = slide3.shapes.add_picture(background_img, left, top, width = pr1.slide_width, height = pr1.slide_height)
slide3.shapes._spTree.insert(2, pic3._element)

# Slide 4

slide4_register = pr1.slide_layouts[5]
slide4 = pr1.slides.add_slide(slide4_register)

title4 = slide4.shapes.title
title4.text = "Art generated by AI"

# AI generated art
img_path = "aigen.png" 
left = Inches(1)
top = Inches(1.5)
width = Inches(8)
height = Inches(5)
slide4.shapes.add_picture(img_path, left, top, width, height)

# Background img

background_img = "wallpaper.png"
left = top = Inches(0)
pic3 = slide4.shapes.add_picture(background_img, left, top, width = pr1.slide_width, height = pr1.slide_height)
slide4.shapes._spTree.insert(2, pic3._element)

# Slide 5

pr1.save('Work_Test.pptx')
